domain_path: /home/user/Documents/Vivado_projects/bmp280/VitisWorkspace/platform/export/platform/sw/standalone_microblaze_0
app_src_dir: /home/user/Tools/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
